name: Check and Execute Rollout
permissions:
  contents: write  # Allow write access to the repository contents (including committing)
  
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes, adjust as needed.
  workflow_dispatch:  # Allows for manual triggering if needed.

jobs:
  check_rollout_schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Rollouts
        id: run-rollout
        shell: pwsh
        run: |
          $serverNameList = @("server1", "server2", "server3") 
          $osType = "Windows" # Example OS type, adjust as needed
          $parentRid = "RID"  # Example RID prefix, adjust as needed

          # Loop through each server in parallel
          $serverIndex = 0
          $serverNameList | ForEach-Object -Parallel {
            param (
              [string]$serverName, 
              [string]$osType, 
              [string]$parentRid, 
              [int]$serverIndex
            )

            # Trim server name (for safety)
            $serverName = $serverName.Trim()
            # Generate unique rollout identifier
            $rid = $parentRid + ($serverIndex + 1).ToString().PadLeft(2, "0")
            $fileName = "$($rid).ini"

            try {
              Write-Host "Running ansible using $($rid).ini - install"
              if ($osType -eq "Windows") {
                echo "rid=$($rid), fileName=$($fileName), serverName=$($serverName), serverIndex=$($serverIndex)"
                
                # Simulate rollout task (replace with your rollout command)
                Start-Sleep -Seconds (Get-Random -Minimum 5 -Maximum 15) 

                if ($LASTEXITCODE -ne 0) {
                  throw "Error installing rollout on server $($serverName)"
                }
              }
            } catch {
              $_
              $validationError = "$($_.Exception.Message)"
              echo "validationError=$($validationError)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
              throw $validationError
            }
          } -ArgumentList $osType, $parentRid, $serverIndex -ThrottleLimit 5
